flowchart TD
    Renters([Renters])
    Providers([Providers])
    
    UserMgmt[User\nManagement]
    Search[Search\nEngine]
    ListingMgmt[Listing\nManagement]
    BookingMgmt[Booking\nManagement]
    Payment[Payment\nProcessing]
    Notification[Notification\nService]
    Review[Review &\nRating]
    Database[(Database\nService)]
    
    Renters -- "Register/Login" --> UserMgmt
    Providers -- "List Items" --> ListingMgmt
    
    UserMgmt -- "Search" --> Search
    Search -- "Display" --> ListingMgmt
    
    UserMgmt -- "Authenticate" --> BookingMgmt
    ListingMgmt -- "Manage Listing" --> BookingMgmt
    
    BookingMgmt -- "Create Booking" --> Payment
    Payment -- "Process" --> Notification
    
    BookingMgmt -- "Store Data" --> Database
    Payment -- "Store Transaction" --> Database
    
    BookingMgmt -- "Store Data" --> Review
    Review -- "Store Data" --> Database
